In [1]:
import numpy as np
#create numpy 1-D array
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [2]:
show=arr[2]
show

3

In [3]:
show=arr[-2]
show

2

In [4]:
#create numpy multi_D array
arr1=np.array([[1,2],[3,4]])
arr1

array([[1, 2],
       [3, 4]])

In [5]:
arr1.shape

(2, 2)

In [6]:
#returns dimensions in array
arr1.ndim

2

In [7]:
#it returns total no. of elements
arr1.size

4

In [8]:
arr1.dtype

dtype('int32')

In [9]:
#it can't create multidimensional if dimensions are not same
arr1=np.array([[1,2,3],[4,5]])
arr1

array([list([1, 2, 3]), list([4, 5])], dtype=object)

In [12]:
arr1=np.array([[1,2,0],[3,4,0],[5,6,0]])
arr1

array([[1, 2, 0],
       [3, 4, 0],
       [5, 6, 0]])

# access element row and col wise

In [13]:
arr1[1:]

array([[3, 4, 0],
       [5, 6, 0]])

In [14]:
arr1=np.array([[1,2,0],[3,4,0],[5,6,0]])
arr1[:,1:]

array([[2, 0],
       [4, 0],
       [6, 0]])

In [15]:
arr1=np.array([[1,2,0],[3,4,0],[5,6,0]])
arr1[0:1,1:2]

array([[2]])

In [16]:
arr1[1][2]

0

# Arithmetic operations in array

In [32]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [18]:
arr+2

array([3, 4, 5])

In [19]:
arr-2

array([-1,  0,  1])

In [20]:
arr*2

array([2, 4, 6])

In [22]:
#exponent 
arr**2

array([1, 4, 9], dtype=int32)

In [24]:
#returns remainder
arr%2

array([1, 0, 1], dtype=int32)

In [25]:
#returns quotient
arr/2

array([0.5, 1. , 1.5])

In [26]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [27]:
b=np.array([7,9,9,4])
b

array([7, 9, 9, 4])

In [28]:
np.add(a,b)# or a+b

array([ 8, 11, 12,  8])

In [29]:
np.multiply(a,b)

array([ 7, 18, 27, 16])

In [30]:
np.power(a,b)

array([    1,   512, 19683,   256], dtype=int32)

In [31]:
np.mod(a,b)

array([1, 2, 3, 0], dtype=int32)